blank_issues_enabled: false
contact_links:
  - name: NÃ¡vrh na tÃ©ma? ğŸ’¡
    url: https://twitter.com/borekb
    about: NapiÅ¡te mi na `borekb@gmail.com` nebo se ozvÄ›te pÅ™es Twitter (@borekb).
  - name: PoÄtÄ›te si v issues
    url: https://github.com/borekb/blog/issues
    about: â†’
